{
 "title": "Schema Registry",
 "tags": [
  "core",
  "schema-registry"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (cluster_id) (kafka_schema_registry_registered_count_registered_count{cluster_id=~\".+\", cluster_type=\"schema-registry\"})",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Schema registered over time",
   "type": "stat",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_schema_registry_master_slave_role_master_slave_role{cluster_id=~\".+\", cluster_type=\"schema-registry\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Schemas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Schema registered over time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(cluster_id) ({__name__=~\"kafka_schema_registry_.+_schemas_created_.+_schemas\", cluster_id=~\".+\", cluster_type=\"schema-registry\"})",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Schemas created",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(cluster_id)({__name__=~\"kafka_schema_registry_.+_schemas_created_.+_schemas\", cluster_id=~\".+\", cluster_type=\"schema-registry\"})",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Schemas deleted",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(cluster_id)({__name__=~\"kafka_schema_registry_.+_schemas_deleted_.+_schemas_deleted\", cluster_id=~\".+\", cluster_type=\"schema-registry\"})",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Schemas created",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster_id, message_format) (\n  label_replace(\n    max by(cluster_id, __name__)(\n      {__name__=~\"kafka_schema_registry_.+_schemas_created_.+_schemas\", cluster_id=~\".+\", cluster_type=\"schema-registry\"}\n    ),\n    \"message_format\",\n    \"$1\",\n    \"__name__\",\n    \"kafka_schema_registry_.+_schemas_created_(.+)_schemas\"\n  )\n)\n",
     "legendFormat": "{{cluster_id}} - {{message_format}} "
    }
   ]
  },
  {
   "title": "Schemas deleted",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster_id, message_format) (\n  label_replace(\n    max by(cluster_id, __name__)(\n      {__name__=~\"kafka_schema_registry_.+_schemas_deleted_.+_schemas_deleted\", cluster_id=~\".+\", cluster_type=\"schema-registry\"}\n    ),\n    \"message_format\",\n    \"$1\",\n    \"__name__\",\n    \"kafka_schema_registry_.+_schemas_deleted_(.+)_schemas_deleted\"\n  )\n)\n",
     "legendFormat": "{{cluster_id}} - {{message_format}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (cluster_id) (kafka_schema_registry_jetty_metrics_connections_active{cluster_id=~\".+\", cluster_type=\"schema-registry\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (cluster_id) (kafka_schema_registry_jersey_metrics_request_rate{cluster_id=~\".+\", cluster_type=\"schema-registry\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Requests latency 99p",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_schema_registry_jersey_metrics_request_latency_99{cluster_id=\"$cluster\", cluster_type=\"schema-registry\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Number of Exporters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (cluster_id) (kafka_schema_registry_exporter_num_exporters{cluster_id=~\".+\", cluster_type=\"schema-registry\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Exporter Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Creatd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_exporters_create_request{cluster_id=~\".+\", cluster_type=\"schema-registry\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_exporters_pause_request{cluster_id=~\".+\", cluster_type=\"schema-registry\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_exporters_resume_request{cluster_id=~\".+\", cluster_type=\"schema-registry\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_exporters_delete_request{cluster_id=~\".+\", cluster_type=\"schema-registry\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}