
lowercaseOutputName: true
rules:
- pattern: java.lang<type=(.*)>
- pattern: "kafka.server<type=app-info, id=(.+)><>(.*): (.*)"
  name: kafka_server_app_info_$2
  labels:
    node_id: "$1"
    kafka_version: "$3"
  value: 1
- pattern: "kafka.server<type=raft-metrics><>current-state: (.+)"
  name: kafka_server_raft_metrics_current_state
  labels:
    state: $1
  value: 1
# Needed for Cluster Linking metrics
# "kafka.server:type=*, name=*, *=*, *=*, *=*, *=*"
#- pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+), (.+)=(.+), (.+)=(.+)><>(Count|Value)
#  name: kafka_$1_$2_$3
#  cache: true
#  labels:
#    "$4": "$5"
#    "$6": "$7"
#    "$8": "$9"
#    "$10": "$11"
- pattern: kafka.(.*)
